mark = 70 grade = None if mark >=70: grade = "A" elif mark >=60: grade = "B"
mark = 60 grade = None if mark >=60: grade = "B" elif mark >=50: grade = "C"
mark = 50 grade = None if mark >=50: grade = "C" elif mark >=40: grade = "D"
mark = 40 grade = None if mark >=40: grade = "D" elif mark >=30: grade = "E"
mark = 30 grade = None if mark >=30: grade = "E" elif mark >=60: grade = "F"
